globalVariables(c(
  ".", "r", "lower", "upper", "pop", "place", "population", "daily_cases",
  "daily_tests", "daily_recovered", "daily_deaths", "total_doses",
  "pct_one_doses", "pct_two_doses", "daily_doses", "date_num", "Mean(R)",
  "Quantile.0.025(R)", "Quantile.0.975(R)", "total_cases", "total_deaths",
  "confirmed", "recovered", "deceased", "state", "district",
  "abbrev",
  "dailyTPR7",
  "dailyCFR7",
  "total_tests",
  "ppt",
  "dailyTPR7d",
  "dailyCFR7d",
  "pct_at_least_one",
  "total_vacc",
  "daily_vax_dose",
  "cfr",
  "cases",
  "deaths",
  "tpr",
  "total_tested",
  "perc_vaccine",
  "pct_second",
  "total cases",
  "7-day average daily CFR",
  "% pop. with two shots",
  "% pop. with at least one shot",
  "# daily new cases",
  "# daily new deaths",
  "7-day average daily TPR",
  "Location",
  "R",
  "daily tests",
  "daily vaccine doses",
  "Total tested",
  "total deaths",
  "Total doses",
  "TPR",
  "total_recovered",
  "date_ymd",
  "daily_confirmed",
  "total_confirmed",
  "daily_deceased",
  "total_deceased",
  "totalpositivecases",
  "totalsamplestested",
  "testedasof",
  "Date",
  "Cases",
  "Tests",
  "country",
  "tests",
  "ns",
  "data",
  "estR0",
  "r_est",
  "r_lower",
  "r_upper",
  "date_ymd",
  "dd",
  "dn",
  "status",
  "Confirmed",
  "Recovered",
  "Deceased",
  "TT",
  "updated_on",
  "vaccinated_as_of",
  "first_dose_administered",
  "second_dose_administered",
  "total_doses_administered",
  "first_dose",
  "second_dose",
  "where"
  )
  )
